### ISSUE TITLE
Cannot find module 'clean-webpack-plugin' when running `npm run build`

### ISSUE THREAD

**Issue by achmadk** [w3id/webunconfid-website#40]
Hello, @tyohan, @ri7nz, and @satyakresna.

I have cloned this repo, then trying to run `npm run build`. Unfortunately I got error like this:

```sh
Error: Cannot find module 'clean-webpack-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (I:\OUTSIDE_PROJECTS\webunconfid-website\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (I:\OUTSIDE_PROJECTS\webunconfid-website\webpack.config.js:7:28)
    at Module._compile (I:\OUTSIDE_PROJECTS\webunconfid-website\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (I:\OUTSIDE_PROJECTS\webunconfid-website\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (I:\OUTSIDE_PROJECTS\webunconfid-website\node_modules\webpack-cli\bin\convert-argv.js:133:13)
    at requireConfig (I:\OUTSIDE_PROJECTS\webunconfid-website\node_modules\webpack-cli\bin\convert-argv.js:135:6)
    at I:\OUTSIDE_PROJECTS\webunconfid-website\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (I:\OUTSIDE_PROJECTS\webunconfid-website\node_modules\webpack-cli\bin\convert-argv.js:140:15)
    at yargs.parse (I:\OUTSIDE_PROJECTS\webunconfid-website\node_modules\webpack-cli\bin\cli.js:241:39)
    at Object.parse (I:\OUTSIDE_PROJECTS\webunconfid-website\node_modules\yargs\yargs.js:563:18)
    at I:\OUTSIDE_PROJECTS\webunconfid-website\node_modules\webpack-cli\bin\cli.js:219:8
    at Object.<anonymous> (I:\OUTSIDE_PROJECTS\webunconfid-website\node_modules\webpack-cli\bin\cli.js:530:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (I:\OUTSIDE_PROJECTS\webunconfid-website\node_modules\webpack\bin\webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
```

Can I create PR to add `clean-webpack-plugin` into devDependencies ?

**Comment by satyakresna** [comment]
Hi @achmadk , yes you can add that package and make PR. I saw the problem like you mention. Thanks.

**Comment by tyohan** [comment]
@achmadk my bad, I add clean-webpack-plugin but didn't push the package json. No need pull request, I will merge the code by today.

**Comment by ri7nz** [comment]
@achmadk  mungkin bisa di close Issuenya karena sudah solve

**Comment by satyakresna** [comment]
@ri7nz , aku lihat di package.json nya di branch master masih belum ada "clean-webpack-plugin" lho. Kayaknya mas @tyohan lupa.

**Comment by tyohan** [comment]
@achmadk belum sempat push, temp solution masukin aja manual nanti tinggal di stash.

**Comment by achmadk** [comment]
yah PR-nya udah keduluan mas @ri7nz mas.
